import type { Metadata } from 'next'
import { Inter, Newsreader } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })
const newsreader = Newsreader({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-newsreader',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="dark">
            <body className={cn(inter.className, newsreader.variable)}>
                {children}
            </body>
        </html>
    )
}
